experiment_dir: /work/hiroace/outputs/run_10yr_ens15/ace2s
n_forward_steps: 14607
forward_steps_in_memory: 50
checkpoint_path: /work/hiroace/data/ACE2S.ckpt
n_ensemble_per_ic: 15

logging:
  log_to_screen: true
  log_to_wandb: false
  log_to_file: true
  project: ace

initial_condition:
  path: /work/hiroace/data/initial_conditions/ic_2014.nc
  start_indices:
    times:
      - "2014-01-01T00:00:00"

forcing_loader:
  dataset:
    data_path: /work/hiroace/data/forcing_data
  num_data_workers: 2

data_writer:
  files:
  - format:
      name: zarr
    label: output_6hourly_ace2s
    names:
    - PRATEsfc
    - UGRD10m
    - VGRD10m
    separate_ensemble_members: true
  save_monthly_files: false
  save_prediction_files: false
